language: python
python: 2.7
env:
  - TOX_ENV=py35-django110
  - TOX_ENV=py35-django19
  - TOX_ENV=py35-django18
  - TOX_ENV=py34-django110
  - TOX_ENV=py34-django19
  - TOX_ENV=py34-django18
  - TOX_ENV=py33-django18
  - TOX_ENV=py32-django18
  - TOX_ENV=py27-django110
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django18
  - TOX_ENV=flake8
  - TOX_ENV=coverage
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
